### ----------------------------------------------------------------
### --- Zmienne Globalne ---
### ----------------------------------------------------------------
@eMechanic.API_HostAddress = http://localhost:5178
@api_version = v1
@base_url = {{eMechanic.API_HostAddress}}/api/{{api_version}}

# --- Zmienne przechwytywane (ustawiane automatycznie) ---
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTlhM2ZhZC1iYzljLTc2NzQtOTdiMy01MzlhODJmZWMxNmMiLCJlbWFpbCI6Im1hY2llai5ub3dha180MkB0ZXN0LmNvbSIsImp0aSI6IjAxOWEzZmFlLWY5ZGEtNzVkYS05NzZkLTdhNTNmZDY2ZDg4NCIsImlkZW50aXR5VHlwZSI6IlVzZXIiLCJ1c2VySWQiOiIwMTlhM2ZhZC1iZWQ0LTdkNDMtYjkxMi05MjA3OTZhNjg2YWUiLCJleHAiOjE3NjIwMDg2MjMsImlzcyI6ImVNZWNoYW5pY0FQSSIsImF1ZCI6ImVNZWNoYW5pY0FQSSJ9.rIj7cY13PZC7qn5mHZ3RpmZZoIM0uTkWJw5ukuKFeUc
@workshopToken =
@userId =
@vehicleId =


### ----------------------------------------------------------------
### --- Users ---
### ----------------------------------------------------------------

### Register User
# @name RegisterUser
POST {{base_url}}/users/register
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Nowak",
  "email": "maciej.nowak15@test.com",
  "password": "Password123!"
}

### Login User (and capture token)
# @name LoginUser
POST {{base_url}}/users/login
Content-Type: application/json

{
    "email": "maciej.nowak_42@test.com",
    "password": "Password123!"
}

> {%
    client.global.set("userToken", response.body.token);
    client.global.set("userId", response.body.userId);
%}

### Get Current User
# @name GetCurrentUser
GET {{base_url}}/users
Authorization: Bearer {{userToken}}
Accept: application/json


### ----------------------------------------------------------------
### --- Workshops ---
### ----------------------------------------------------------------

### Register Workshop
# @name RegisterWorkshop
POST {{base_url}}/workshops/register
Content-Type: application/json

{
  "email": "workshop_{{$randomInt}}@example.com",
  "password": "Password123!",
  "contactEmail": "contact_{{$randomInt}}@workshop.com",
  "name": "Super Warsztat",
  "displayName": "SuperW_{{$randomInt}}",
  "phoneNumber": "123456789",
  "address": "ul. Testowa 1",
  "city": "Poznań",
  "postalCode": "60-123",
  "country": "Polska"
}

### Login Workshop (and capture token)
# @name LoginWorkshop
POST {{base_url}}/workshops/login
Content-Type: application/json

{
    "email": "workshop_1@example.com",
    "password": "Password123!"
}

> {%
    client.global.set("workshopToken", response.body.token);
%}

### Get All Workshops (Paginated)
# @name GetAllWorkshops
GET {{base_url}}/workshops?pageNumber=1&pageSize=10
Accept: application/json

### Create Vehicle
# @name CreateVehicle
POST {{base_url}}/vehicles
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "vin": "VIN{{$randomInt}}ABC12DS345d6",
  "manufacturer": "Test Manufacturer",
  "model": "Test Model",
  "productionYear": "2023",
  "engineCapacity": 1.9,
  "mileage": 125000,
  "mileageUnit": 1,
  "fuelType": 1,
  "bodyType": 1,
  "vehicleType": 1
}

> {%
    client.global.set("vehicleId", response.body.vehicleId);
%}

### Get Vehicle By ID
# @name GetVehicleById
GET {{base_url}}/vehicles/{{vehicleId}}
Authorization: Bearer {{userToken}}
Accept: application/json

### Get All Vehicles
# @name GetAllVehicles
GET {{base_url}}/vehicles?pageNumber=1&pageSize=5
Authorization: Bearer {{userToken}}
Accept: application/json

### Update Vehicle
# @name UpdateVehicle
PUT {{base_url}}/vehicles/{{vehicleId}}
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "vin": "VIN{{$randomInt}}XYZ987654",
  "manufacturer": "Updated Manufacturer",
  "model": "Updated Model S",
  "productionYear": "2024",
  "engineCapacity": 2.5,
  "mileage": 130000,
  "mileageUnit": "Kilometers",
  "fuelType": "Electric",
  "bodyType": "Hatchback",
  "vehicleType": "Passenger"
}

### Delete Vehicle
# @name DeleteVehicle
DELETE {{base_url}}/vehicles/{{vehicleId}}
Authorization: Bearer {{userToken}}
