name: Deploy API to Azure App Service

on:
  push:
    branches:
      - main 
    paths:
      - 'src/eMechanic.Backend/**'
      - '.github/workflows/deploy-azure.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package API
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/eMechanic.Backend/eMechanic.sln

      - name: Build API Project
        run: dotnet build src/eMechanic.Backend/Core/src/eMechanic.API/eMechanic.API.csproj --configuration Release --no-restore

      - name: Publish API Project
        run: dotnet publish src/eMechanic.Backend/Core/src/eMechanic.API/eMechanic.API.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: api-app 
          path: ./publish

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build 
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: api-app 

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06CA4A04193C45C1BFDB2D14681EB597 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F63489E157184C80A665EDDC7DD2EC1A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2DBFE6844D834F2AB17B9AC6A4A91D05 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp 
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e-mechanic-core-api' 
          slot-name: 'Production' 
          package: .
